
WISELIB_PATH=/home/wiselib/wiselib

WISELIB_STABLE=$(WISELIB_PATH)/wiselib.stable
WISELIB_TESTING=$(WISELIB_PATH)/wiselib.testing

CXX=clang++-3.3
LD=ld
CXXFLAGS+=-I$(WISELIB_STABLE) -I$(WISELIB_TESTING) -Os -fdiagnostics-show-template-tree
#-fno-elide-type
LDFLAGS+= -lpthread -lrt 

$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) $< -o $@ $(LDFLAGS)

clean:
	find . -executable -type f -delete

all: clean $(TARGET)

debug: LDFLAGS+= -g -DDEBUG
debug: all